export const movieContent = [
    {
        id: 1,
        contentType: "MOVIE",
        title: "인터스텔라",
        thumbnailUrl: "/images/interstellar.jpg",
        releaseDate: "2014-11-06",
        ageRating: "12",
        genres: ["SF", "드라마"],
        score: 9.1,
    },
    {
        id: 2,
        contentType: "MOVIE",
        title: "인터스텔라",
        thumbnailUrl: "/images/interstellar.jpg",
        releaseDate: "2014-11-06",
        ageRating: "12",
        genres: ["SF", "드라마"],
        score: 9.1,
    },
    {
        id: 3,
        contentType: "MOVIE",
        title: "인터스텔라",
        thumbnailUrl: "/images/interstellar.jpg",
        releaseDate: "2014-11-06",
        ageRating: "12",
        genres: ["SF", "드라마"],
        score: 9.1,
    },
    {
        id: 4,
        contentType: "MOVIE",
        title: "인터스텔라",
        thumbnailUrl: "/images/interstellar.jpg",
        releaseDate: "2014-11-06",
        ageRating: "12",
        genres: ["SF", "드라마"],
        score: 9.1,
    },
];